# Generated by Django 3.2 on 2021-04-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SenorModel',
            new_name='SensorModel',
        ),
    ]
